table inventory_snapshots
	lineageTag: 413ba3fff6cc7cd55dd07ec6a54ce2ec

	partition inventory_snapshots = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/juanj/OneDrive/Documents/Data Analysis Projects/supply_chain_inventory/python/data/processed/inventory_snapshots_clean.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"product_id", Int64.Type}, {"snapshot_date", type date}, {"stock_on_hand", Int64.Type}, {"stockout", Int64.Type}})
				in
				    ChangedType

	column product_id
		dataType: int64
		summarizeBy: none
		sourceColumn: product_id

	column snapshot_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: snapshot_date

	column stock_on_hand
		dataType: int64
		summarizeBy: none
		sourceColumn: stock_on_hand

	column stockout
		dataType: int64
		summarizeBy: none
		sourceColumn: stockout

	measure 'Total Stock On Hand' = SUM(inventory_snapshots[stock_on_hand])
		formatString: #,0

	measure 'Inventory Value' = SUMX(inventory_snapshots, inventory_snapshots[stock_on_hand] * RELATED(products[unit_cost]))
		formatString: $#,0

	measure 'Latest Snapshot Date' = MAX(inventory_snapshots[snapshot_date])
		formatString: Short Date

	measure 'Latest Stock On Hand' = VAR LatestDate = [Latest Snapshot Date] RETURN CALCULATE([Total Stock On Hand], inventory_snapshots[snapshot_date] = LatestDate)
		formatString: #,0

	measure 'Latest Inventory Value' = VAR LatestDate = [Latest Snapshot Date] RETURN CALCULATE([Inventory Value], inventory_snapshots[snapshot_date] = LatestDate)
		formatString: $#,0

	measure 'Stockout Weeks' = SUM(inventory_snapshots[stockout])
		formatString: #,0

	measure 'Stockout Rate %' = DIVIDE([Stockout Weeks], COUNTROWS(inventory_snapshots))
		formatString: 0.0%

	measure 'Products Stocked Out' = COUNTROWS(FILTER(VALUES(products[product_name]), CALCULATE(MAX(inventory_snapshots[stockout])) = 1))
		formatString: #,0

	measure 'Worst Product' = CONCATENATEX(TOPN(1, VALUES(products[product_name]), [Stockout Rate %], DESC), products[product_name], ", ")

	measure 'Worst Product Stockout Rate %' = MAXX(TOPN(1, VALUES(products[product_name]), [Stockout Rate %], DESC), [Stockout Rate %])
		formatString: 0.0%

	measure 'Average Product Stockout Rate %' = AVERAGEX(VALUES(products[product_name]), [Stockout Rate %])
		formatString: 0.0%

	measure 'Stockout Bar' = ```
			VAR Rate = [Stockout Rate %]
			VAR Scale = 0.35
			VAR BarW = 300
			VAR W = MAX(1, MIN(BarW, DIVIDE(Rate, Scale) * BarW))
			VAR Fill = IF(Rate >= 0.20, "#D4602E", IF(Rate >= 0.10, "#B9C3CF", "#2B7A78"))
			RETURN
				"data:image/svg+xml;utf8," &
				"<svg xmlns='http://www.w3.org/2000/svg' width='" & BarW & "' height='18'>" &
				"<rect x='0' y='6' width='" & BarW & "' height='6' rx='3' fill='#E6EAEF'/>" &
				"<rect x='0' y='6' width='" & FORMAT(W, "0") & "' height='6' rx='3' fill='" & Fill & "'/>" &
				"</svg>"
		```
		dataCategory: ImageUrl
