table products
	lineageTag: 33b10979ebd6322c01bddb9a55104801

	partition products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/juanj/OneDrive/Documents/Data Analysis Projects/supply_chain_inventory/python/data/processed/products_clean.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"product_id", Int64.Type}, {"product_name", type text}, {"category", type text}, {"supplier_id", Int64.Type}, {"unit_cost", type number}, {"reorder_point", Int64.Type}, {"order_quantity", Int64.Type}})
				in
				    ChangedType

	column product_id
		dataType: int64
		summarizeBy: none
		sourceColumn: product_id

	column product_name
		dataType: string
		summarizeBy: none
		sourceColumn: product_name

	column category
		dataType: string
		summarizeBy: none
		sourceColumn: category

	column supplier_id
		dataType: int64
		summarizeBy: none
		sourceColumn: supplier_id

	column unit_cost
		dataType: decimal
		summarizeBy: none
		sourceColumn: unit_cost

	column reorder_point
		dataType: int64
		summarizeBy: none
		sourceColumn: reorder_point

	column order_quantity
		dataType: int64
		summarizeBy: none
		sourceColumn: order_quantity
