table purchase_orders
	lineageTag: ec8ea63331f1fd2e400ee113e97bd376

	partition purchase_orders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/juanj/OneDrive/Documents/Data Analysis Projects/supply_chain_inventory/python/data/processed/purchase_orders_clean.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"po_id", Int64.Type}, {"product_id", Int64.Type}, {"supplier_id", Int64.Type}, {"order_date", type date}, {"expected_delivery_date", type date}, {"actual_delivery_date", type date}, {"quantity_ordered", Int64.Type}})
				in
				    ChangedType

	column po_id
		dataType: int64
		summarizeBy: none
		sourceColumn: po_id

	column product_id
		dataType: int64
		summarizeBy: none
		sourceColumn: product_id

	column supplier_id
		dataType: int64
		summarizeBy: none
		sourceColumn: supplier_id

	column order_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: order_date

	column expected_delivery_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: expected_delivery_date

	column actual_delivery_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: actual_delivery_date

	column quantity_ordered
		dataType: int64
		summarizeBy: none
		sourceColumn: quantity_ordered

	measure 'Total Orders' = COUNTROWS(purchase_orders)
		formatString: #,0

	measure 'On-Time Orders' = CALCULATE(COUNTROWS(purchase_orders), purchase_orders[actual_delivery_date] <= purchase_orders[expected_delivery_date])
		formatString: #,0

	measure 'On-Time %' = DIVIDE([On-Time Orders], [Total Orders])
		formatString: 0.0%

	measure 'Late Orders' = [Total Orders] - [On-Time Orders]
		formatString: #,0

	measure 'Supplier Count' = DISTINCTCOUNT(suppliers[supplier_id])
		formatString: #,0

	measure 'Lowest On-Time Supplier' = CONCATENATEX(TOPN(1, VALUES(suppliers[supplier_name]), [On-Time %], ASC), suppliers[supplier_name], ", ")

	measure 'Lowest Supplier On-Time %' = MINX(VALUES(suppliers[supplier_name]), [On-Time %])
		formatString: 0.0%
