table suppliers
	lineageTag: 269913465a41b406bfa078da35e74f91

	partition suppliers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "suppliers_clean.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"supplier_id", Int64.Type}, {"supplier_name", type text}, {"region", type text}, {"nominal_lead_time_days", Int64.Type}}),
				    UnknownMember = Table.InsertRows(ChangedType, Table.RowCount(ChangedType), {[supplier_id = -1, supplier_name = "No supplier on record", region = "Unassigned", nominal_lead_time_days = null]})
				in
				    UnknownMember

	column supplier_id
		dataType: int64
		summarizeBy: none
		sourceColumn: supplier_id

	column supplier_name
		dataType: string
		summarizeBy: none
		sourceColumn: supplier_name

	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region

	column nominal_lead_time_days
		dataType: int64
		summarizeBy: none
		sourceColumn: nominal_lead_time_days
