table lines
	lineageTag: 8d4e1acb6e156cec9573b8328c9785b0

	partition lines = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/juanj/OneDrive/Documents/Data Analysis Projects/industry_operations_cost/python/data/processed/lines_clean.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"line_id", Int64.Type}, {"line_name", type text}, {"area", type text}, {"target_units_per_hour", Int64.Type}})
				in
				    ChangedType

	column line_id
		dataType: int64
		summarizeBy: none
		sourceColumn: line_id

	column line_name
		dataType: string
		summarizeBy: none
		sourceColumn: line_name

	column area
		dataType: string
		summarizeBy: none
		sourceColumn: area

	column target_units_per_hour
		dataType: int64
		summarizeBy: none
		sourceColumn: target_units_per_hour
