table monthly_costs
	lineageTag: a3dd6b5f6fe2728c3e22d9bc13ae497d

	partition monthly_costs = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/juanj/OneDrive/Documents/Data Analysis Projects/industry_operations_cost/python/data/processed/monthly_costs_clean.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"cost_id", Int64.Type}, {"line_id", Int64.Type}, {"cost_month", type text}, {"cost_type", type text}, {"amount", type number}})
				in
				    ChangedType

	column cost_id
		dataType: int64
		summarizeBy: none
		sourceColumn: cost_id

	column line_id
		dataType: int64
		summarizeBy: none
		sourceColumn: line_id

	column cost_month
		dataType: string
		summarizeBy: none
		sourceColumn: cost_month

	column cost_type
		dataType: string
		summarizeBy: none
		sourceColumn: cost_type

	column amount
		dataType: decimal
		summarizeBy: none
		sourceColumn: amount

	measure 'Total Cost' = SUM(monthly_costs[amount])
		formatString: $#,0

	measure 'Cost per Unit' = DIVIDE([Total Cost], [Total Units])
		formatString: $0.00

	measure 'Materials Cost' = CALCULATE([Total Cost], monthly_costs[cost_type] = "Materials")
		formatString: $#,0

	measure 'Materials Share %' = DIVIDE([Materials Cost], [Total Cost])
		formatString: 0.0%

	measure 'Maintenance Cost' = CALCULATE([Total Cost], monthly_costs[cost_type] = "Maintenance")
		formatString: $#,0

	measure 'Maintenance Share %' = DIVIDE([Maintenance Cost], [Total Cost])
		formatString: 0.0%

	measure 'Highest Cost Type' = CONCATENATEX(TOPN(1, VALUES(monthly_costs[cost_type]), [Total Cost], DESC), monthly_costs[cost_type], ", ")
